#root -l -b -q FullFastSimScaleFactor.cpp;
root -l -b -q WTagScaleFactor.cpp;
cd plot/;
rm -rf FastSimFullSimScaleFactor;
rm -rf TopTagEfficiency;
rm -rf WTagEfficiency;
mkdir FastSimFullSimScaleFactor;
mkdir TopTagEfficiency;
mkdir WTagEfficiency;
mv *Gen* FastSimFullSimScaleFactor/;
mv *Top* TopTagEfficiency/;
mv *png WTagEfficiency/;
cd FastSimFullSimScaleFactor/;
mkdir Top;
mkdir W;
mv *GenTop* Top/;
mv *png W/;
cd ../../;
